# Generated by Django 5.1.2 on 2024-10-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя/Фамилия')),
                ('phone', models.IntegerField(max_length=15, verbose_name='Номер телефона')),
                ('date', models.DateTimeField(verbose_name='Дата обращения')),
            ],
        ),
    ]
