# Generated by Django 5.1.2 on 2024-10-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0002_alter_articles_options_alter_articles_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='date',
            new_name='created_at',
        ),
    ]
