# Generated by Django 5.1.2 on 2024-10-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0003_rename_date_articles_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='created_at',
            new_name='date',
        ),
    ]
