# Generated by Django 5.1.2 on 2024-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0004_rename_created_at_articles_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='articles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
